bot:
    token: ${BOT_TOKEN}
    username: ${BOT_USERNAME}
    temp-chat-id: ${BOT_TEMP_CHAT_ID}

server:
    port: 443
    ssl:
        key-store: classpath:yaremax-keystore.jks
        key-store-password: ${SSL_KEY_STORE_PASSWORD}
        key-store-type: JKS
