bot:
    token: ${env.TELEGRAM_BOT_TOKEN}
    username: ${env.TELEGRAM_BOT_USERNAME}
    temp-chat-id: ${env.TELEGRAM_PRIMARY_CHAT_ID}

server:
    port: 443
    ssl:
        key-store: classpath:yaremax-keystore.p12
        key-store-password: ${env.SSL_KEY_STORE_PASSWORD}
        key-store-type: pkcs12
        key-alias: ${env.SSL_KEY_ALIAS}
        key-password: ${env.SSL_KEY_PASSWORD}