bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    temp-chat-id: ${TELEGRAM_PRIMARY_CHAT_ID}

server:
    port: 443
    ssl:
        key-store: classpath:yaremax-keystore.jks
        key-store-password: ${SSL_KEY_STORE_PASSWORD}
        key-store-type: JKS
