name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Set up JDK 17 and Maven
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
  
        - name: Build and push Docker image
          run: |
            mvn clean package -P build-docker-image -DskipTests 

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}

      # - name: Install Docker Compose
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker
      #     sudo apt-get install -y docker-compose
  
      - name: Build and run Docker Compose services
        run: |
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          BOT_TEMP_CHAT_ID=${{ secrets.BOT_TEMP_CHAT_ID }}
          BOT_USERNAME=${{ secrets.BOT_USERNAME }}
          export BOT_TOKEN BOT_TEMP_CHAT_ID BOT_USERNAME
          docker-compose up -d
