name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
          
  #       - name: Set up JDK 17 and Maven
  #         uses: actions/setup-java@v3
  #         with:
  #           java-version: '17'
  #           distribution: 'temurin'
  #           cache: maven

  #       - name: Login to Docker Hub
  #         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

  #       - name: Build and push Docker image
  #         run: |
  #           mvn clean package -P build-docker-image -DskipTests 

  deploy:
    # needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Logs
        run: |
          pwd
          ls -la
        
    
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          passphrase: ${{ secrets.DIGITAL_OCEAN_SSH_PASSPHRASE }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: /home
    
      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DIGITAL_OCEAN_SSH_PASSPHRASE }}

      - name: Install Docker Compose
        run: |
          ls /home
          sudo apt-get update
          sudo apt-get install -y docker
          sudo apt-get install -y docker-compose
  
      - name: Build and run Docker Compose services
        run: |
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          BOT_TEMP_CHAT_ID=${{ secrets.BOT_TEMP_CHAT_ID }}
          BOT_USERNAME=${{ secrets.BOT_USERNAME }}
          export BOT_TOKEN BOT_TEMP_CHAT_ID BOT_USERNAME
          docker-compose up -d
